version: '3'

services:
  vault-maxi:
    image: vault-maxi:v2.5.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VAULT_MAXI_VERSION: v2.5.0
        VAULT_MAXI_REPO_URL: https://github.com/kuegi/defichain_maxi.git
    volumes:
      - /opt/vault-maxi:/root/.vault-maxi
    environment:
      - TRIGGER_MINS=10 #trigger every x minutes
    restart: always
